#!/bin/bash
set -euxo pipefail
# Cloud Run Button insists on pushing, so we get a light one from Github and push that

# Better option but only listens to port 8000 so stuck until: https://github.com/GoogleCloudPlatform/cloud-run-button/issues/185
# docker pull crccheck/hello-world
# docker tag crccheck/hello-world gcr.io/${GOOGLE_CLOUD_PROJECT}/${K_SERVICE}
docker pull gcr.io/rowy-run/rowy-deploy
docker tag gcr.io/rowy-run/rowy-deploy gcr.io/${GOOGLE_CLOUD_PROJECT}/${K_SERVICE}